version: '2'

# Named volumes
volumes:
  # MySQL Data
  wscompra-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - wscompra-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=wscompra
      - MYSQL_DATABASE=wscompra
      - MYSQL_USER=wscompra
      - MYSQL_PASSWORD=wscompra
  
# PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - db
